In [14]:
# Setup
!pip install pandas numpy
import pandas as pd

df0 = pd.read_csv('railway_delays_2020_01_1.csv')
df0.head()
weather = pd.read_csv('weather.csv')

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [15]:
#Uses a list comprehension to create a list of the filenames 
# from January 1st, 2020  to January 27th,2020

filenames = ['railway_delays_2020_01_' + str(i) + '.csv' for i in range(1,28)]
print(filenames)

['railway_delays_2020_01_1.csv', 'railway_delays_2020_01_2.csv', 'railway_delays_2020_01_3.csv', 'railway_delays_2020_01_4.csv', 'railway_delays_2020_01_5.csv', 'railway_delays_2020_01_6.csv', 'railway_delays_2020_01_7.csv', 'railway_delays_2020_01_8.csv', 'railway_delays_2020_01_9.csv', 'railway_delays_2020_01_10.csv', 'railway_delays_2020_01_11.csv', 'railway_delays_2020_01_12.csv', 'railway_delays_2020_01_13.csv', 'railway_delays_2020_01_14.csv', 'railway_delays_2020_01_15.csv', 'railway_delays_2020_01_16.csv', 'railway_delays_2020_01_17.csv', 'railway_delays_2020_01_18.csv', 'railway_delays_2020_01_19.csv', 'railway_delays_2020_01_20.csv', 'railway_delays_2020_01_21.csv', 'railway_delays_2020_01_22.csv', 'railway_delays_2020_01_23.csv', 'railway_delays_2020_01_24.csv', 'railway_delays_2020_01_25.csv', 'railway_delays_2020_01_26.csv', 'railway_delays_2020_01_27.csv']

In [16]:
#Use a list comprehension to create a list of DataFrames named railway_delays_dfs

railway_delays_dfs = [pd.read_csv(filename) for filename in filenames]

#concatenates multiple datasets of railway_delays_2020 and prints summary information about it

railway_delays_full = pd.concat(railway_delays_dfs)

railway_delays_full.info()

<class 'pandas.DataFrame'>
Index: 29717 entries, 0 to 1081
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               28604 non-null  str
 1   ride_id            28604 non-null  str
 2   train_number       28604 non-null  str
 3   station_order      28604 non-null  float64
 4   station_name       27491 non-null  str
 5   to_station         28604 non-null  str
 6   mileage            28604 non-null  float64
 7   arrival_delay      28604 non-null  float64
 8   departure_delay    28604 non-null  float64
 9   major_holiday      28604 non-null  object
 10  DATE               1113 non-null   str
 11  RIDE_ID            1113 non-null   str
 12  TRAIN_NUMBER       1113 non-null   str
 13  STATION_ORDER      1113 non-null   float64
 14  STATION_NAME       1113 non-null   str
 15  TO_STATION         1113 non-null   str
 16  MILEAGE            1113 non-null   float64
 17  ARRIVAL_DELAY      1113 non-null   float64
 18  DEPARTURE_DELAY    1113 non-null   float64
 19  MAJOR_HOLIDAY      1113 non-null   object
 20  station_name       1113 non-null   str
dtypes: float64(8), object(2), str(11)
memory usage: 5.0+ MB

In [17]:
for df in railway_delays_dfs: 
    df.columns = df.columns.str.lower() 
    df.columns = df.columns.str.strip() 


railway_delays_full = pd.concat(railway_delays_dfs) 
railway_delays_full.info()

<class 'pandas.DataFrame'>
Index: 29717 entries, 0 to 1081
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             29717 non-null  str
 1   ride_id          29717 non-null  str
 2   train_number     29717 non-null  str
 3   station_order    29717 non-null  float64
 4   station_name     29717 non-null  str
 5   to_station       29717 non-null  str
 6   mileage          29717 non-null  float64
 7   arrival_delay    29717 non-null  float64
 8   departure_delay  29717 non-null  float64
 9   major_holiday    29717 non-null  bool
dtypes: bool(1), float64(4), str(5)
memory usage: 2.3 MB

In [18]:
for col in railway_delays_full.columns:

    #uppercase and strip any hidden extra whitespace in all the object datatype columns

    if railway_delays_full[col].dtypes == 'object': 
        railway_delays_full[col] = railway_delays_full[col].str.upper()
        railway_delays_full[col] = railway_delays_full[col].str.strip() 

    #convert all float datatype columns to integers
    elif railway_delays_full[col].dtypes == 'float64':
        railway_delays_full[col] = railway_delays_full[col].astype('int64')


railway_delays_full.info()

<class 'pandas.DataFrame'>
Index: 29717 entries, 0 to 1081
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             29717 non-null  str
 1   ride_id          29717 non-null  str
 2   train_number     29717 non-null  str
 3   station_order    29717 non-null  int64
 4   station_name     29717 non-null  str
 5   to_station       29717 non-null  str
 6   mileage          29717 non-null  int64
 7   arrival_delay    29717 non-null  int64
 8   departure_delay  29717 non-null  int64
 9   major_holiday    29717 non-null  bool
dtypes: bool(1), int64(4), str(5)
memory usage: 2.3 MB

In [19]:
#Impact of Holiday Travel
#amount of train rides occurred on major holidays 

railway_delays_full_mayor_holiday_count_true = railway_delays_full['major_holiday'].value_counts()[True]

railway_delays_full_mayor_holiday_count_false = railway_delays_full['major_holiday'].value_counts()[False]
#print('The amount of train rides occurred on major holidays is: ', railway_delays_full_mayor_holiday_count_true)
#print('The amount of train rides occurred on non-holidays is: ', railway_delays_full_mayor_holiday_count_false)

#calculates the average of arrival_delay and departure_delay
railway_delays_full_by_major_holiday = railway_delays_full.groupby(['major_holiday']).agg({'arrival_delay':'mean','departure_delay':'mean',}).reset_index()
column_mapper = {'arrival_delay' : 'avg_arrival_delay', 'departure_delay':'avg_departure_delay' }
railway_delays_full_by_major_holiday = railway_delays_full_by_major_holiday.rename(mapper=column_mapper, axis=1)

railway_delays_full_by_major_holiday

   major_holiday  avg_arrival_delay  avg_departure_delay
0          False          23.367881            22.362104
1           True          23.815863            22.924193

In [20]:
#Compute descriptive summary statistics on the distances from station to station
railway_delays_full['mileage'].describe()

count    29717.000000
mean        88.000236
std         79.537992
min          1.000000
25%         43.000000
50%         70.000000
75%        120.000000
max       1410.000000
Name: mileage, dtype: float64

In [21]:
#checks if longer-than-average distances correspond to longer delays

railway_delays_full['long_distance'] = railway_delays_full['mileage'] > 88
railway_delays_full.head()

,date,ride_id,train_number,station_order,station_name,to_station,mileage,arrival_delay,departure_delay,major_holiday,long_distance
0,2020-01-01,G1226_20200101_1,G1226,1,Shenyangbei Railway Station,Shenyang Railway Station,5,0,-1,True,False
1,2020-01-01,G1226_20200101_2,G1226,2,Shenyang Railway Station,Liaoyang Railway Station,65,-2,2,True,False
2,2020-01-01,G1226_20200101_3,G1226,3,Liaoyang Railway Station,Anshanxi Railway Station,30,4,4,True,False
3,2020-01-01,G1226_20200101_4,G1226,4,Anshanxi Railway Station,Haichengxi Railway Station,39,5,4,True,False
4,2020-01-01,G1226_20200101_5,G1226,5,Haichengxi Railway Station,Panjin Railway Station,66,5,4,True,False

In [22]:
#calculate the average arrival_delay and departure_delay

railway_delays_arrival_departure_avg_delay = railway_delays_full.groupby(['long_distance']).agg({'arrival_delay':'mean','departure_delay':'mean',}).reset_index()

column_mapper = {'arrival_delay' : 'avg_arrival_delay', 'departure_delay':'avg_departure_delay' }
railway_delays_arrival_departure_avg_delay = railway_delays_arrival_departure_avg_delay.rename(mapper=column_mapper, axis=1)

railway_delays_arrival_departure_avg_delay

   long_distance  avg_arrival_delay  avg_departure_delay
0          False          16.578222            15.120508
1           True          34.611244            34.385746

In [23]:
weather.head()

            ride_id                      wind weather  temperature
0  G1226_20200101_1    light winds from the N   sunny         -7.0
1  G1226_20200101_2    light winds from the N   sunny         -7.0
2  G1226_20200101_3    light winds from the N   sunny         -3.0
3  G1226_20200101_4  gentle breeze from the N   sunny         -3.0
4  G1226_20200101_5  gentle breeze from the N   sunny         -3.0

In [24]:
#clean weather data


for col in weather.columns:

    #uppercase and strip any hidden extra whitespace in all the object datatype columns

    if weather[col].dtypes == 'object': 
        weather[col] = weather[col].str.upper()
        weather[col] = weather[col].str.strip() 

    #convert all float datatype columns to integers
    elif weather[col].dtypes == 'float64':
        weather[col] = weather[col].astype('int64')


railway_delays_full.info()

<class 'pandas.DataFrame'>
Index: 29717 entries, 0 to 1081
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             29717 non-null  str
 1   ride_id          29717 non-null  str
 2   train_number     29717 non-null  str
 3   station_order    29717 non-null  int64
 4   station_name     29717 non-null  str
 5   to_station       29717 non-null  str
 6   mileage          29717 non-null  int64
 7   arrival_delay    29717 non-null  int64
 8   departure_delay  29717 non-null  int64
 9   major_holiday    29717 non-null  bool
 10  long_distance    29717 non-null  bool
dtypes: bool(2), int64(4), str(5)
memory usage: 2.3 MB

In [25]:
#Merge weather with railway_delays_full using the ride_id column

railway_delays_join_weather = pd.merge(left = weather,
right = railway_delays_full,
left_on = 
'ride_id',
right_on = 
'ride_id',
how = 'inner')

railway_delays_join_weather.head()

,ride_id,wind,weather,temperature,date,train_number,station_order,station_name,to_station,mileage,arrival_delay,departure_delay,major_holiday,long_distance
0,G1226_20200101_1,light winds from the N,sunny,-7,2020-01-01,G1226,1,Shenyangbei Railway Station,Shenyang Railway Station,5,0,-1,True,False
1,G1226_20200101_2,light winds from the N,sunny,-7,2020-01-01,G1226,2,Shenyang Railway Station,Liaoyang Railway Station,65,-2,2,True,False
2,G1226_20200101_3,light winds from the N,sunny,-3,2020-01-01,G1226,3,Liaoyang Railway Station,Anshanxi Railway Station,30,4,4,True,False
3,G1226_20200101_4,gentle breeze from the N,sunny,-3,2020-01-01,G1226,4,Anshanxi Railway Station,Haichengxi Railway Station,39,5,4,True,False
4,G1226_20200101_5,gentle breeze from the N,sunny,-3,2020-01-01,G1226,5,Haichengxi Railway Station,Panjin Railway Station,66,5,4,True,False

In [28]:
#calculate the average of arrival_delay and departure_delay because of weather.
#Sort the result from highest arrival_delay to lowest.

railway_delays_join_weather_arr_dep_avg_delay = railway_delays_join_weather.groupby(['weather']).agg({'arrival_delay':'mean','departure_delay':'mean',}).reset_index()
 
column_mapper = {'arrival_delay' : 'avg_arrival_delay', 'departure_delay':'avg_departure_delay' }
railway_delays_join_weather_arr_dep_avg_delay = railway_delays_join_weather_arr_dep_avg_delay.rename(mapper=column_mapper, axis=1)

railway_delays_join_weather_arr_dep_avg_delay.sort_values(by='avg_arrival_delay', ascending=False)

                   weather  avg_arrival_delay  avg_departure_delay
0                 blizzard         314.666667           314.666667
6               heavy snow          79.289157            78.590361
12           moderate snow          67.816794            66.977099
8               light snow          50.243197            49.719388
16                   sleet          39.614767            39.579454
11           moderate rain          39.065776            37.885920
1                   cloudy          28.314811            27.243096
18                   sunny          23.074158            21.916419
14                overcast          19.193166            18.550558
7               light rain          15.308342            14.110996
15                 showers           7.551724             7.195402
17            snow showers           3.527027             3.229730
9   light to moderate rain           2.960000             1.184615
2                 downpour           2.571429             1.771429
13  moderate to heavy rain           0.833333             0.333333
3                      fog           0.689922             0.031008
10           moderate haze           0.650943             0.490566
4                     haze           0.501946             0.163424
5               heavy haze          -0.125000            -0.166667